CREATE DATABASE IF NOT EXISTS kutuphaneOtomasyon3;

USE kutuphaneOtomasyon3;

CREATE TABLE T_KATEGORI(
	kategoriID INT AUTO_INCREMENT PRIMARY KEY,
    kategoriAd VARCHAR(40) 
);

CREATE TABLE T_YAYINEVI(
	yayineviID INT AUTO_INCREMENT PRIMARY KEY,
    yayineviAd VARCHAR(40),
    yayineviUlke VARCHAR(20)    
);

-- YAZAR ILE YAYINEVI N:N BAGLANTILI JOINT TABLE YAPACAGIZ VE 
-- T_KITAPTA T_YAYINEVI ILE ILISKILI BU SEBEPLE O TABLO OLUSTURULMADAN BAGLANTIYI KURMAMIZ GEREKIYOR
CREATE TABLE T_YAZAR( 
	yazarID INT AUTO_INCREMENT PRIMARY KEY,
    yazarUlke VARCHAR(15),
    yazarAd VARCHAR(20),
    yazarSoyad VARCHAR(20)
);
-- YAZAR VE YAYINEVI PRIMARY KEYINI ALACAGIZ
CREATE TABLE T_YAZAR_YAYINEVI_JT( -- BU TABLO UZERINDEN N:N ILISKIYI YAZAR<-1:N->JT<-N:1->YAYINEVI SEKLINDE IMPLEMENTE ETTIK
	yazarID INT,
    yayineviID INT,
    PRIMARY KEY(yazarID,yayıneviID),

    FOREIGN KEY (yazarID) REFERENCES T_YAZAR(yazarID),
    FOREIGN KEY (yayineviID) REFERENCES T_YAYINEVI(yayineviID)

    -- YAZAR TAM AD ICIN PROSEDUR YAZILACAK
);

CREATE TABLE T_KITAP(
	kitapID INT AUTO_INCREMENT PRIMARY KEY,
    kitapAd VARCHAR(40) ,
    kitapStok INT,
    kitapFiyat DECIMAL(6,2),
    kitapISBN CHAR(13),
    kitapSayfaSayisi INT,
    
    kategoriID INT,
	yayineviID INT,

    
    FOREIGN KEY (kategoriID) REFERENCES T_KATEGORI(kategoriID), -- 1 KATEGORI N KITAP BAGLANTISI
    FOREIGN KEY (yayineviID) REFERENCES T_YAYINEVI(yayineviID)  -- 1 YAYINEVI N KITAP BAGLANTISI
);

ALTER TABLE T_KITAP
MODIFY kitapISBN CHAR(20);

CREATE TABLE T_KITAP_YAZAR_JT (
    kitapID INT,
    yazarID INT,
    PRIMARY KEY (kitapID, yazarID),
    FOREIGN KEY (kitapID) REFERENCES T_KITAP(kitapID),
    FOREIGN KEY (yazarID) REFERENCES T_YAZAR(yazarID)
);




CREATE TABLE T_UYELER(
	uyeID INT AUTO_INCREMENT PRIMARY KEY,
    uyeCinsiyet ENUM('E','K'),
    uyeAd VARCHAR(30),
    uyelikUcreti DECIMAL(4,1),
    uyeKayitTarih DATETIME,
    uyeIndirimMiktari DECIMAL(3,1),
    uyeTCNO char(11) UNIQUE,				-- ---------------------------------------------YENI EKLENDI
    
    uyeTuru ENUM('OGRENCI','SIVIL','OZELSEKTOR')
    -- YAS BURADAN PROSEDURLE TURETILEBILIR
);

CREATE TABLE T_OGRENCI( -- T_UYELER TABLOSUNDAN OVERLAP
	ogrenciID INT AUTO_INCREMENT PRIMARY KEY,
    ogrenciOkulAd VARCHAR(50),
    ogrenciTuru ENUM('LISANS','LISANSUSTU','ORTAOGRETIM'),
    
    uyeID INT, 
    FOREIGN KEY (uyeID) REFERENCES T_UYELER(uyeID) -- 1 T_UYE <-> N T_OGRENCI
);
-- T_OGRENCI TABLOSUNDAN DISJOINT YAPILMISTIR
CREATE TABLE T_LISANS(
	lisansID INT AUTO_INCREMENT PRIMARY KEY,
    lisansBolum VARCHAR(25),
    lisansAGNO DECIMAL(3,2), 
    CHECK(lisansAGNO <= 4.0),
    
    ogrenciID INT UNIQUE,
    FOREIGN KEY (ogrenciID) REFERENCES T_OGRENCI(ogrenciID)
);

-- T_OGRENCI TABLOSUNDAN DISJOINT YAPILMISTIR
CREATE TABLE T_ORTAOGRETIM(
	ortaogretimID INT AUTO_INCREMENT PRIMARY KEY,
	ortaogretimSinif INT, 
    ortaogretimOrtalama INT, 
    ortaOgretimTuru ENUM('ILKOKUL','ORTAOKUL','LISE'),
    
    ogrenciID INT UNIQUE,
    FOREIGN KEY (ogrenciID) REFERENCES T_OGRENCI(ogrenciID)   
);

-- T_OGRENCI TABLOSUNDAN DISJOINT YAPILMISTIR
CREATE TABLE T_LISANSUSTU(
	lisansUstuID INT AUTO_INCREMENT PRIMARY KEY,
	lisansBolum VARCHAR(25),
    lisansUstuAGNO DECIMAL(3,2), -- AGNOYA KISITLMA KOYULMALI 4.00 UZERINE GECEMEMELIDIR
    CHECK (lisansUstuAGNO <= 4.00),
   
    ogrenciID INT UNIQUE,
	FOREIGN KEY (ogrenciID) REFERENCES T_OGRENCI(ogrenciID)
);

CREATE TABLE T_SIVIL( -- T_UYELER TABLOSUNDAN OVERLAP				-- --------EMEKLI OLARAK DEGISTIRILEBILIRS
	sivilID INT AUTO_INCREMENT PRIMARY KEY,
    sivilGelirMiktar DECIMAL(6,2),
    
    uyeID INT,
	FOREIGN KEY (uyeID) REFERENCES T_UYELER(uyeID) -- 1 T_UYE <-> N T_SIVIL
);

CREATE TABLE T_OZELSEKTOR( -- T_UYELER TABLOSUNDAN OVERLAP
	ozelSektorID INT AUTO_INCREMENT PRIMARY KEY,
    ozelSektorKurumAntlasma BOOL,
    uyeID INT,
	FOREIGN KEY (uyeID) REFERENCES T_UYELER(uyeID) -- 1 T_UYE <-> N T_OZELSEKTOR
);


-- ZAYIF VARLIK : KITAP ILE ARASINDA VAROLMA BAGIMLILIGI VAR
CREATE TABLE T_ODUNC(
	oduncID INT AUTO_INCREMENT PRIMARY KEY,
    oduncAlmaTarih DATETIME,
    iadeEtmeTarih DATETIME,
    
    -- 
    kitapID INT , -- ZAYIF VARLIK OLDUGUNDAN ICINDE BAGIMLI OLDUGUNUN PK'SINI EKLEDIK
    uyeID INT,
    
    FOREIGN KEY (kitapID) REFERENCES T_KITAP(kitapID),
    FOREIGN KEY (uyeID) REFERENCES T_UYELER(uyeID) 
);

-- PERSONELIN KITAPLA MANTIKSAL BIR BAGLANTISI YOK
CREATE TABLE T_PERSONEL(
	personelID INT AUTO_INCREMENT PRIMARY KEY,
    personelAd VARCHAR(20),
    personelSoyad VARCHAR(20),
    personelMaas DECIMAL(7,2),
    personelTuru ENUM('HIZMETLI','YONETICI')
);

CREATE TABLE T_HIZMETLI(
	hizmetliID INT AUTO_INCREMENT PRIMARY KEY,
    hizmetliGorev VARCHAR(1000),
	
    personelID INT UNIQUE, 
    FOREIGN KEY (personelID) REFERENCES T_PERSONEL(personelID) 
);

CREATE TABLE T_YONETICI(
	yoneticiID INT AUTO_INCREMENT PRIMARY KEY,
    yoneticiBirim VARCHAR(50),

    personelID INT UNIQUE, 
    FOREIGN KEY (personelID) REFERENCES T_PERSONEL(personelID) 
);

SELECT TK.kitapID, 
       TK.kitapAd, 
       TK.kitapStok, 
       TK.kitapISBN, 
       TKategori.kategoriAd, 
       TK.kitapSayfaSayisi, 
       TK.kitapFiyat, 
       TYayin.yayineviAd, 
       TYazar.yazarAd, 
       TYazar.yazarSoyad
FROM T_KITAP TK
JOIN T_KATEGORI TKategori ON TK.kategoriID = TKategori.kategoriID
JOIN T_YAYINEVI TYayin ON TK.yayineviID = TYayin.yayineviID
JOIN T_KITAP_YAZAR_JT TKYazarJT ON TK.kitapID = TKYazarJT.kitapID
JOIN T_YAZAR TYazar ON TKYazarJT.yazarID = TYazar.yazarID;
